### ISSUE TITLE
Info: Implementing compilation targets

### ISSUE THREAD

**Issue by colelawrence** [paulstansifer/unseemly#35]
Hi again,

First, thank you for the prompt follow-up to #34. A lot of the syntax is starting to fall into place for me.

One of my favorite things about your approach is that your language comprises of the minimum constructs needed for building a typed language out of macros. Therefore, I would imagine that compared to other languages, the surface area for implementing alternative compile targets becomes a bit easier since most of the language constructs live on macros.

From your perspective, is it any easier to implement other targets because of the current design?

I was wondering what you thought about exploring Cranelift as a backend. Alternatively, I would be interested in exploring the Erlang BEAM as a target since there aren't many typed languages targeting that ecosystem yet.

Perhaps this is just a conversation starter for now.

**Comment by paulstansifer** [comment]
I think that this discussion should be merged into issue #12; I'll close this issue as a duplicate (I've added a comment there). Please add any more thoughts you have there!
